### PR TITLE
i18n markup added

### PR DESCRIPTION
**Pull request by BloodSakura3774**
I used regular expressions to do the markup.
Both logging and output/display strings are marked.
I'm not sure about some of them so please double check my work before merging. And I'm not certain about some of the formated, please notice me if the format isn't right and I'll fix them. I might added too much or missed some.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Does the code still run? Have you tested it?

**Comment by BloodSakura3774** [comment]
> Does the code still run? Have you tested it?

Didn’t test it, I don’t think the code will run without implementing the library first.
Will test later

**Comment by BloodSakura3774** [comment]
> Does the code still run? Have you tested it?

It won't run without gettext is implemented, 
**Syntax error in ...\MethodicConfigurator\ardupilot_methodic_configurator.py
  File "...\MethodicConfigurator\ardupilot_methodic_configurator.py", line 50
     _('parameters. The GUI reads intermediate parameter files from a directory and ')
     ^
 SyntaxError: invalid syntax**

**Comment by amilcarlucas** [comment]
This week I'm really busy can add commits that start the gettext implementation?

**Comment by BloodSakura3774** [comment]
I can try to finish this

**Comment by BloodSakura3774** [comment]
implemented, and tested that it works.
only thing left is exporting those marked string and translate them.
Also it is currently set to zh-cn in the new file **internationalization.py** 
I believe we will need to compile multiple .exe for release after this is merged.

**Comment by BloodSakura3774** [comment]
Yes it will be better but there is more work to do by distributing a single .exe.
TBH, some chinese users can not read any english so setting the language when installing might be "difficult" for them. If we are doing only chinese translation for now, I think it's better to distribute two .exe.
I'm available during the weekend so can you start extrating those marked strings?

**Comment by amilcarlucas** [comment]
This branch produces a chinese .exe file. The .po file is ready for translation and there is a script to generate the .mo file.

Can you take it from here and add the translation? I will add the language selection at the beginning of the installer later.

**Comment by amilcarlucas** [comment]
An improved version of this got merged, thanks for helping out.
See details in https://github.com/ArduPilot/MethodicConfigurator/commit/3ca5a385b34612e9949a94cd5d6193e51c458a49

Please open a new pull-request on top of master

**Comment by BloodSakura3774** [comment]
I'll try finishing it this weekend. There is more string than I thought would be. I'm trying to make it as natural as possible.

**Pull request closed without merging**
